#!/bin/sh
#
# Install this plugin and provider in the LCG GIP version 1.0.21 or later with
#
#  > ln -s /opt/d-cache/jobs/infoDynamicSE-plugin-dcache /opt/lcg/var/gip/plugin/
#  > ln -s /opt/d-cache/jobs/infoDynamicSE-provider-dcache /opt/lcg/var/gip/provider/
#
# The plugin will only print the entries of ${infoProviderStaticFile} which should
# be changed. The provider will print access and control protocol entries according
# to the running services.
#

. /opt/d-cache/config/dCacheSetup

${java:-java} -jar /opt/d-cache/classes/infoDynamicSE.jar                                    \
              -mode=plugin                                                                   \
              -ldif=${infoProviderStaticFile:-/opt/lcg/var/gip/ldif/lcg-info-static-se.ldif} \
              -type=dcache                                                                   \
              -host=${infoCollectorHost:-$(hostname)}                                        \
              -port=${infoCollectorPort:-22111}
