#!/bin/sh -f
#
# Usage: srm-can-access (get|put) <path> [<user>]

. /local/ups/etc/setups.sh
setup dfarm

dir=$1
path=$2
user=$3

answer="false"

if [ "$dir" = "get" ]
then
	sts=`dfarm info -0 $path`
	if [ "$sts" = "f" ]
	then
		answer="true"
	fi
else
	answer="true"
fi

echo $answer
