/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v3.xdr;
/**
 * Enumeration (collection of constants).
 */
public interface mountstat3 {

    public static final int MNT3_OK = 0;
    public static final int MNT3ERR_PERM = 1;
    public static final int MNT3ERR_NOENT = 2;
    public static final int MNT3ERR_IO = 5;
    public static final int MNT3ERR_ACCES = 13;
    public static final int MNT3ERR_NOTDIR = 20;
    public static final int MNT3ERR_INVAL = 22;
    public static final int MNT3ERR_NAMETOOLONG = 63;
    public static final int MNT3ERR_NOTSUPP = 10004;
    public static final int MNT3ERR_SERVERFAULT = 10006;

}
// End of mountstat3.java
