/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v3.xdr;
import org.dcache.xdr.*;
import java.io.IOException;

public class entryplus3 implements XdrAble {
    public fileid3 fileid;
    public filename3 name;
    public cookie3 cookie;
    public post_op_attr name_attributes;
    public post_op_fh3 name_handle;
    public entryplus3 nextentry;

    public entryplus3() {
    }

    public entryplus3(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        entryplus3 $this = this;
        do {
            $this.fileid.xdrEncode(xdr);
            $this.name.xdrEncode(xdr);
            $this.cookie.xdrEncode(xdr);
            $this.name_attributes.xdrEncode(xdr);
            $this.name_handle.xdrEncode(xdr);
            $this = $this.nextentry;
            xdr.xdrEncodeBoolean($this != null);
        } while ( $this != null );
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        entryplus3 $this = this;
        entryplus3 $next;
        do {
            $this.fileid = new fileid3(xdr);
            $this.name = new filename3(xdr);
            $this.cookie = new cookie3(xdr);
            $this.name_attributes = new post_op_attr(xdr);
            $this.name_handle = new post_op_fh3(xdr);
            $next = xdr.xdrDecodeBoolean() ? new entryplus3() : null;
            $this.nextentry = $next;
            $this = $next;
        } while ( $this != null );
    }

}
// End of entryplus3.java
