/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v3.xdr;

import java.io.IOException;

import org.dcache.xdr.OncRpcException;
import org.dcache.xdr.XdrAble;
import org.dcache.xdr.XdrDecodingStream;
import org.dcache.xdr.XdrEncodingStream;

public class mountres3_ok implements XdrAble {
    public fhandle3 fhandle;
    public int [] auth_flavors;

    public mountres3_ok() {
    }

    public mountres3_ok(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    @Override
    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        fhandle.xdrEncode(xdr);
        xdr.xdrEncodeIntVector(auth_flavors);
    }

    @Override
    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        fhandle = new fhandle3(xdr);
        auth_flavors = xdr.xdrDecodeIntVector();
    }

}
// End of mountres3_ok.java
