/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v3.xdr;
import org.dcache.xdr.*;
import java.io.IOException;

public class PATHCONF3resok implements XdrAble {
    public post_op_attr obj_attributes;
    public uint32 linkmax;
    public uint32 name_max;
    public boolean no_trunc;
    public boolean chown_restricted;
    public boolean case_insensitive;
    public boolean case_preserving;

    public PATHCONF3resok() {
    }

    public PATHCONF3resok(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    @Override
    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        obj_attributes.xdrEncode(xdr);
        linkmax.xdrEncode(xdr);
        name_max.xdrEncode(xdr);
        xdr.xdrEncodeBoolean(no_trunc);
        xdr.xdrEncodeBoolean(chown_restricted);
        xdr.xdrEncodeBoolean(case_insensitive);
        xdr.xdrEncodeBoolean(case_preserving);
    }

    @Override
    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        obj_attributes = new post_op_attr(xdr);
        linkmax = new uint32(xdr);
        name_max = new uint32(xdr);
        no_trunc = xdr.xdrDecodeBoolean();
        chown_restricted = xdr.xdrDecodeBoolean();
        case_insensitive = xdr.xdrDecodeBoolean();
        case_preserving = xdr.xdrDecodeBoolean();
    }

}
// End of PATHCONF3resok.java
