/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v3.xdr;
import org.dcache.xdr.*;
import java.io.IOException;

public class post_op_fh3 implements XdrAble {
    public boolean handle_follows;
    public nfs_fh3 handle;

    public post_op_fh3() {
    }

    public post_op_fh3(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    @Override
    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeBoolean(handle_follows);
        if ( handle_follows ) {
            handle.xdrEncode(xdr);
        }
    }

    @Override
    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        handle_follows = xdr.xdrDecodeBoolean();
        if ( handle_follows ) {
            handle = new nfs_fh3(xdr);
        }
    }

}
// End of post_op_fh3.java
