/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v3.xdr;

import java.io.IOException;

import org.dcache.xdr.OncRpcException;
import org.dcache.xdr.XdrAble;
import org.dcache.xdr.XdrDecodingStream;
import org.dcache.xdr.XdrEncodingStream;

public class READ3resok implements XdrAble {
    public post_op_attr file_attributes;
    public count3 count;
    public boolean eof;
    public byte [] data;

    public READ3resok() {
    }

    public READ3resok(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    @Override
    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        file_attributes.xdrEncode(xdr);
        count.xdrEncode(xdr);
        xdr.xdrEncodeBoolean(eof);
        xdr.xdrEncodeDynamicOpaque(data);
    }

    @Override
    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        file_attributes = new post_op_attr(xdr);
        count = new count3(xdr);
        eof = xdr.xdrDecodeBoolean();
        data = xdr.xdrDecodeDynamicOpaque();
    }

}
// End of READ3resok.java
