/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v3.xdr;
import org.dcache.xdr.*;
import java.io.IOException;

public class RENAME3resok implements XdrAble {
    public wcc_data fromdir_wcc;
    public wcc_data todir_wcc;

    public RENAME3resok() {
    }

    public RENAME3resok(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    @Override
    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        fromdir_wcc.xdrEncode(xdr);
        todir_wcc.xdrEncode(xdr);
    }

    @Override
    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        fromdir_wcc = new wcc_data(xdr);
        todir_wcc = new wcc_data(xdr);
    }

}
// End of RENAME3resok.java
