// $Id: ClientV1.java,v 1.12 2005-03-11 21:18:35 timur Exp $
// $Log: not supported by cvs2svn $
// Revision 1.11  2005/01/25 23:20:20  timur
// srmclient now uses srm libraries
//
// Revision 1.10  2004/07/02 20:14:21  timur
// reformated code a bit
//
// Revision 1.9  2004/06/30 21:57:03  timur
//  added retries on each step, added the ability to use srmclient used by srm copy in the server, added srm-get-request-status
//

/*
COPYRIGHT STATUS:
  Dec 1st 2001, Fermi National Accelerator Laboratory (FNAL) documents and
  software are sponsored by the U.S. Department of Energy under Contract No.
  DE-AC02-76CH03000. Therefore, the U.S. Government retains a  world-wide
  non-exclusive, royalty-free license to publish or reproduce these documents
  and software for U.S. Government purposes.  All documents and software
  available from this server are protected under the U.S. and Foreign
  Copyright Laws, and FNAL reserves all rights.
 
 
 Distribution of the software available from this server is free of
 charge subject to the user following the terms of the Fermitools
 Software Legal Information.
 
 Redistribution and/or modification of the software shall be accompanied
 by the Fermitools Software Legal Information  (including the copyright
 notice).
 
 The user is asked to feed back problems, benefits, and/or suggestions
 about the software to the Fermilab Software Providers.
 
 
 Neither the name of Fermilab, the  URA, nor the names of the contributors
 may be used to endorse or promote products derived from this software
 without specific prior written permission.
 
 
 
  DISCLAIMER OF LIABILITY (BSD):
 
  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
  "AS IS" AND ANY EXPRESS OR IMPLIED  WARRANTIES, INCLUDING, BUT NOT
  LIMITED TO, THE IMPLIED  WARRANTIES OF MERCHANTABILITY AND FITNESS
  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL FERMILAB,
  OR THE URA, OR THE U.S. DEPARTMENT of ENERGY, OR CONTRIBUTORS BE LIABLE
  FOR  ANY  DIRECT, INDIRECT,  INCIDENTAL, SPECIAL, EXEMPLARY, OR
  CONSEQUENTIAL DAMAGES  (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
  OF SUBSTITUTE  GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
  BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY  OF
  LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
  NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT  OF THE USE OF THIS
  SOFTWARE, EVEN IF ADVISED OF THE  POSSIBILITY OF SUCH DAMAGE.
 
 
  Liabilities of the Government:
 
  This software is provided by URA, independent from its Prime Contract
  with the U.S. Department of Energy. URA is acting independently from
  the Government and in its own private capacity and is not acting on
  behalf of the U.S. Government, nor as its contractor nor its agent.
  Correspondingly, it is understood and agreed that the U.S. Government
  has no connection to this software and in no manner whatsoever shall
  be liable for nor assume any responsibility or obligation for any claim,
  cost, or damages arising out of or resulting from the use of the software
  available from this server.
 
 
  Export Control:
 
  All documents and software available from this server are subject to U.S.
  export control laws.  Anyone downloading information from this server is
  obligated to secure any necessary Government licenses before exporting
  documents or software obtained from this server.
 */

// generated by GLUE/wsdl2java on Mon Jun 17 15:36:22 CDT 2002
package gov.fnal.srm.client;

import electric.registry.Registry;
import electric.registry.RegistryException;
import diskCacheV111.srm.ISRM;
import org.dcache.srm.SRMException;
import org.dcache.srm.Logger;
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.net.URLConnection;
import java.net.HttpURLConnection;

public class ClientV1 {
    public static final short DEFAULTPORT=8004;
    public static final String DEFAULTPATH="srm/srmserverv1.wsdl";
    private ISRM manager;
    
    public ClientV1(Logger logger) throws SRMException {
        this("localhost",logger);
    }
    
    public ClientV1(String host,Logger logger) throws SRMException {
        this(host,DEFAULTPORT,logger);
    }
    
    public ClientV1(String host,short port,Logger logger) throws SRMException {
        this(host,port,DEFAULTPATH,logger);
    }
    
    public ClientV1(String host,short port,String path,Logger logger) throws SRMException {
        this("http",host,port,path,logger);
    }
    
    public ClientV1(String protocol, String host,short port,String path,Logger logger) throws SRMException {
        System.setProperty("electric.wsdl.targetNamespace","srm.1.0.ns");
        String wsdl_url =null;
        if(protocol.equals("file")) {
            wsdl_url =protocol+":///"+path;
        }
        else {
            if(port == 80) {
                protocol = "http";
            }
            wsdl_url =protocol+"://" + host + ":"+port+"/"+path;
        }
        logger.log(" wsdl url is "+wsdl_url);
        wsdl_url = unwrapHttpRedirection(wsdl_url);
        logger.log("unwrapped wsdl url is "+wsdl_url);
        
        logger.log("connecting to "+wsdl_url);
        
        try {
            manager =(ISRM) Registry.bind(wsdl_url,ISRM.class);
        }
        catch(Exception e) {
        /*if(!protocol.equals("file"))
        {
            try
            {
                wsdl_url =protocol+"://" + host + ":"+port+"/castor/"+path;
                logger.log("connecting to "+wsdl_url);
                manager =(ISRM) Registry.bind(wsdl_url,ISRM.class);
            }
            catch(Exception e1)
            {
              e1.printStackTrace();
              throw new SRMException(e.toString()+" and "+e1.toString());
            }
        }
        else
        {*/
            e.printStackTrace();
            throw new SRMException(e.toString());
            /*}*/
        }
        if(manager == null) {
            throw new SRMException();
        }
    }
    
    public ISRM getManagerConnection() {
        return manager;
    }
    
    public static ISRM bind( String url ) throws RegistryException {
        return (ISRM) Registry.bind( url, ISRM.class );
    }
    
    public static String unwrapHttpRedirection(String http_url) {
        if(http_url == null || !http_url.startsWith("http://")) {
            return http_url;
        }
        HttpURLConnection http_connection  = null;
        InputStream in = null;
        try {
            URL http_URL = new URL(http_url);
            URLConnection connection = http_URL.openConnection();
            connection.setDoInput(true);
            connection.setDoOutput(false);
            if(connection instanceof  HttpURLConnection) {
                http_connection = (HttpURLConnection) connection;
                http_connection.setInstanceFollowRedirects(true);
                in = http_connection.getInputStream(); //this force the reading of the header
                URL new_url = http_connection.getURL();
                return new_url.toString();
                
            }
            
        }
        catch(IOException ioe) {
            
        }
        finally {
            try {
                if(in != null) {
                    in.close();
                }
                if(http_connection != null) {
                    http_connection.disconnect();
                }
            }
            catch(IOException ioe) {
            }
        }
        return http_url;
    }
    
}
