/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v3.xdr;
import org.dcache.xdr.*;
import java.io.IOException;
import java.util.Arrays;

public class cookieverf3 implements XdrAble {

    public byte [] value;

    public cookieverf3() {
    }

    public cookieverf3(byte [] value) {
        this.value = value;
    }

    public cookieverf3(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeOpaque(value, nfs3_prot.NFS3_COOKIEVERFSIZE);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        value = xdr.xdrDecodeOpaque(nfs3_prot.NFS3_COOKIEVERFSIZE);
    }

    @Override
    public int hashCode() {
        return Arrays.hashCode(value);
    }

    @Override
    public boolean equals(Object obj) {

        if( obj == this ) return true;

        if( !(obj instanceof cookieverf3) ) return false;

        return Arrays.equals(this.value, ((cookieverf3)obj).value );
    }

}
// End of cookieverf3.java
