/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v3.xdr;
/**
 * Enumeration (collection of constants).
 */
public interface createmode3 {

    public static final int UNCHECKED = 0;
    public static final int GUARDED = 1;
    public static final int EXCLUSIVE = 2;

}
// End of createmode3.java
