/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v3.xdr;
import org.dcache.xdr.*;
import java.io.IOException;

public class fhstatus implements XdrAble {
    public int fhs_status;
    public fhandle2 fhs_fhandle;

    public fhstatus() {
    }

    public fhstatus(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeInt(fhs_status);
        switch ( fhs_status ) {
        case 0:
            fhs_fhandle.xdrEncode(xdr);
            break;
        default:
            break;
        }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        fhs_status = xdr.xdrDecodeInt();
        switch ( fhs_status ) {
        case 0:
            fhs_fhandle = new fhandle2(xdr);
            break;
        default:
            break;
        }
    }

}
// End of fhstatus.java
