/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v3.xdr;
/**
 * Enumeration (collection of constants).
 */
public interface time_how {

    public static final int DONT_CHANGE = 0;
    public static final int SET_TO_SERVER_TIME = 1;
    public static final int SET_TO_CLIENT_TIME = 2;

}
// End of time_how.java
