#
# kafka service
#
apiVersion: v1
kind: Service
metadata:
  name: billing-kafka
spec:
  selector:
    app: kafka
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
---


#
# kafka
#
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: apache/kafka:3.9.1
          ports:
            - name: kafka
              containerPort: 9092
          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 10
            timeoutSeconds: 5
          env:
          - name: KAFKA_LISTENERS
            value: PLAINTEXT://:9092,CONTROLLER://:9093
          - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            value: "1"
          - name: KAFKA_ADVERTISED_LISTENERS
            value: PLAINTEXT://billing-kafka:9092
          - name: KAFKA_CONTROLLER_QUORUM_VOTERS
            value: 1@localhost:9093
          - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
            value: "1"
          - name: KAFKA_CONTROLLER_LISTENER_NAMES
            value: CONTROLLER
          - name: KAFKA_NODE_ID
            value: "1"
          - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
            value: "0"
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            value: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
          - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
            value: "1"
          - name: KAFKA_PROCESS_ROLES
            value: broker,controller
