### copy endpoint without authentication
POST {{schema-host-port}}/{{api}}/{{v1}}/migrations/copy
accept: application/json
Content-Type: application/json

{
  "sourcePool": "pool_res2",
  "targetPools": [
    "pool_res3"
  ]
}


> {%
    client.test("Request without authentication", function() {
        client.assert(response.status === 401, "Response status is not 401 - Unauthorized");
    });
%}


### copy endpoint without authentication
POST {{schema-host-port}}/{{api}}/{{v1}}/migrations/copy
Content-Type: application/json


{
  "sourcePool": {{sourcePool}},
  "targetPools": [{{targetPools}}]
}

> {%
    client.test("Request without authentication and with passed in variables ", function() {
        client.assert(response.status === 401, "Response status is not 401 - Unauthorized");
    });
%}


### copy endpoint with authentication
POST {{schema-host-port}}/{{api}}/{{v1}}/migrations/copy
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

{
  "sourcePool": {{sourcePool}},
  "targetPools": [{{targetPools}}]
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}


### copy endpoint with content-type json
POST {{schema-host-port}}/{{api}}/{{v1}}/migrations/copy
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

{
  "sourcePool": {{sourcePool}},
  "targetPools": [{{targetPools}}]
}
> {%
    client.test("Response content-type is json", function() {
        var type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });
%}


### test if response body is empty
POST {{schema-host-port}}/{{api}}/{{v1}}/migrations/copy
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

{
  "sourcePool": {{sourcePool}},
  "targetPools": [{{targetPools}}]
}

> {%
    client.test("Response body is empty(null)", function() {
        client.assert(response.body === null, "Response body was not null");
    });
%}

### copy endpoint - bad request when sourcePool is not provided
POST {{schema-host-port}}/{{api}}/{{v1}}/migrations/copy
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

{
  "targetPools": [{{targetPools}}]
}

> {%
    client.test("Response is Bad request", function() {
        client.assert(response.status === 400, "Response status is not 400");
    });
%}


### copy endpoint - bad request when targetPool is not provided
POST {{schema-host-port}}/{{api}}/{{v1}}/migrations/copy
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

{
  "sourcePool": {{sourcePool}}

}

> {%
    client.test("Response is Bad request", function() {
        client.assert(response.status === 400, "Response status is not 400");
    });
%}

### copy endpoint - bad request when sourcePool is incorrect
POST {{schema-host-port}}/{{api}}/{{v1}}/migrations/copy
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

{
  "sourcePool": {{wrong_src_pool_name}},
  "targetPools": [{{targetPools}}]
}

> {%
    client.test("Response is Bad request", function() {
        client.assert(response.status === 400, "Response status is not 400");
    });
%}


### copy endpoint - bad request when targetPool is incorrect
POST {{schema-host-port}}/{{api}}/{{v1}}/migrations/copy
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

{
  "sourcePool": {{sourcePool}},
  "targetPools": [{{wrong_target_pool_name}}]
}

> {%
    client.test("Response is Bad request", function() {
        client.assert(response.status === 400, "Response status is not 400");
    });
%}

### copy endpoint - bad request when targetPools array has no length
POST {{schema-host-port}}/{{api}}/{{v1}}/migrations/copy
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

{
  "sourcePool": {{sourcePool}},
  "targetPools": []
}

> {%
    client.test("Response is Bad request", function() {
        client.assert(response.status === 400, "Response status is not 400");
    });
%}

### copy endpoint - bad request when provided array of targetPools
POST {{schema-host-port}}/{{api}}/{{v1}}/migrations/copy
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

{
  "sourcePool": {{sourcePool}},
  "targetPools": [{{targetPools}}, {{wrong_target_pool_name}}]
}

> {%
    client.test("Response is Bad request", function() {
        client.assert(response.status === 400, "Response status is not 400");
    });
%}

### copy endpoint - bad request when cocurrency is provided
//TODO: concurrency should be a whole number
POST {{schema-host-port}}/{{api}}/{{v1}}/migrations/copy
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

{
  "sourcePool": {{sourcePool}},
  "targetPools": [{{targetPools}}],
  "concurrency": 3.98
}

> {%
    client.test("Response is Bad request", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### copy endpoint - create request when sourcePool is not provided
POST {{schema-host-port}}/{{api}}/{{v1}}/migrations/copy
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

{
  "sourcePool": {{sourcePool}},
  "targetPools": [{{targetPools}}],
  "pins": "keep"
}

> {%
    client.test("Response is create request", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### copy endpoint - create request when pins attribute set to move
POST {{schema-host-port}}/{{api}}/{{v1}}/migrations/copy
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

{
  "sourcePool": {{sourcePool}},
  "targetPools": [{{targetPools}}],
  "pins": "move"
}

> {%
    client.test("Response is create request", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### copy endpoint - create request when smode attribute set to same
POST {{schema-host-port}}/{{api}}/{{v1}}/migrations/copy
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

{
  "sourcePool": {{sourcePool}},
  "targetPools": [{{targetPools}}],
  "smode": "same"
}

> {%
    client.test("Response is create request", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### copy endpoint - create request when smode attribute set to cached
POST {{schema-host-port}}/{{api}}/{{v1}}/migrations/copy
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

{
  "sourcePool": {{sourcePool}},
  "targetPools": [{{targetPools}}],
  "smode": "cached"
}

> {%
    client.test("Response is create request", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}
### copy endpoint - create request when smode attribute set to precious
POST {{schema-host-port}}/{{api}}/{{v1}}/migrations/copy
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

{
  "sourcePool": {{sourcePool}},
  "targetPools": [{{targetPools}}],
  "smode": "precious"
}

> {%
    client.test("Response is create request", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### copy endpoint - create request when smode attribute set to removable
POST {{schema-host-port}}/{{api}}/{{v1}}/migrations/copy
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

{
  "sourcePool": {{sourcePool}},
  "targetPools": [{{targetPools}}],
  "smode": "removable"
}

> {%
    client.test("Response is create request", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### copy endpoint - create request when smode attribute set to delete
POST {{schema-host-port}}/{{api}}/{{v1}}/migrations/copy
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

{
  "sourcePool": {{sourcePool}},
  "targetPools": [{{targetPools}}],
  "smode": "delete"
}

> {%
    client.test("Response is create request", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### copy endpoint - create request when smode attribute set to delete+u2
POST {{schema-host-port}}/{{api}}/{{v1}}/migrations/copy
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

{
  "sourcePool": {{sourcePool}},
  "targetPools": [{{targetPools}}],
  "smode": "delete+u2"
}

> {%
    client.test("Response is create request", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### copy endpoint - create request when tmode attribute set to same
POST {{schema-host-port}}/{{api}}/{{v1}}/migrations/copy
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

{
  "sourcePool": {{sourcePool}},
  "targetPools": [{{targetPools}}],
  "tmode": "same"
}

> {%
    client.test("Response is create request", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### copy endpoint - create request when tmode attribute set to cached
POST {{schema-host-port}}/{{api}}/{{v1}}/migrations/copy
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

{
  "sourcePool": {{sourcePool}},
  "targetPools": [{{targetPools}}],
  "tmode": "cached"
}

> {%
    client.test("Response is create request", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### copy endpoint - create request when tmode attribute set to precious
POST {{schema-host-port}}/{{api}}/{{v1}}/migrations/copy
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

{
  "sourcePool": {{sourcePool}},
  "targetPools": [{{targetPools}}],
  "tmode": "precious"
}

> {%
    client.test("Response is create request", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### copy endpoint - create request when verify attribute set to true
POST {{schema-host-port}}/{{api}}/{{v1}}/migrations/copy
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

{
  "sourcePool": {{sourcePool}},
  "targetPools": [{{targetPools}}],
  "verify": true
}

> {%
    client.test("Response is create request", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### copy endpoint - create request when verify attribute set to false
POST {{schema-host-port}}/{{api}}/{{v1}}/migrations/copy
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

{
  "sourcePool": {{sourcePool}},
  "targetPools": [{{targetPools}}],
  "verify": false
}

> {%
    client.test("Response is create request", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### copy endpoint - create request when eager attribute set to true
POST {{schema-host-port}}/{{api}}/{{v1}}/migrations/copy
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

{
  "sourcePool": {{sourcePool}},
  "targetPools": [{{targetPools}}],
  "eager": true
}

> {%
    client.test("Response is crete request", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### copy endpoint - create request when eager attribute set to false
POST {{schema-host-port}}/{{api}}/{{v1}}/migrations/copy
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

{
  "sourcePool": {{sourcePool}},
  "targetPools": [{{targetPools}}],
  "eager": false
}

> {%
    client.test("Response is create request", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### copy endpoint - create request when exclude attribute set
POST {{schema-host-port}}/{{api}}/{{v1}}/migrations/copy
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

{
  "sourcePool": {{sourcePool}},
  "targetPools": [{{targetPools}}],
  "exclude": [{{excludePools}}]
}

> {%
    client.test("Response is create request", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### copy endpoint - create request when include attribute set
POST {{schema-host-port}}/{{api}}/{{v1}}/migrations/copy
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

{
  "sourcePool": {{sourcePool}},
  "targetPools": [{{targetPools}}],
  "include" : [{{includePools}}]
}


> {%
    client.test("Response is create request", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### copy endpoint - create request when refresh attribute set
POST {{schema-host-port}}/{{api}}/{{v1}}/migrations/copy
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

{
  "sourcePool": {{sourcePool}},
  "targetPools": [{{targetPools}}],
  "refresh" : {{refresh}}
}


> {%
    client.test("Response is create request", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### copy endpoint - create request when refresh select set
POST {{schema-host-port}}/{{api}}/{{v1}}/migrations/copy
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

{
  "sourcePool": {{sourcePool}},
  "targetPools": [{{targetPools}}],
  "select" : "proportional"
}


> {%
    client.test("Response is create request", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### copy endpoint - create request when target attribute set to hsm
POST {{schema-host-port}}/{{api}}/{{v1}}/migrations/copy
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

{
  "sourcePool": {{sourcePool}},
  "target": {{target}},
  "targetPools": [{{osm_targetPools}}]
}


> {%
    client.test("Response is create request", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### copy endpoint - create request when select attribute set
POST {{schema-host-port}}/{{api}}/{{v1}}/migrations/copy
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

{
  "sourcePool": {{sourcePool}},
  "targetPools": [{{targetPools}}],
  "select" : "random"
}


> {%
    client.test("Response is create request", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### copy endpoint - create request when target attribute set to pool
POST {{schema-host-port}}/{{api}}/{{v1}}/migrations/copy
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

{
  "sourcePool": {{sourcePool}},
  "targetPools": [{{targetPools}}],
  "target" : "pool"
}


> {%
    client.test("Response is create request", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### copy endpoint - create request when target attribute set to pgroup
#POST {{schema-host-port}}/{{api}}/{{v1}}/migrations/copy
#Content-Type: application/json
#Authorization: Basic {{user_name}} {{passwd}}
#
#{
#  "sourcePool": {{sourcePool}},
#  "targetPools": [{{targetPools}}],
#  "target" : "pgroup"
#}
#
#
#> {%
#    client.test("Response is create request", function() {
#        client.assert(response.status === 201, "Response status is not 201");
#    });
#%}

### copy endpoint - create request when target attribute set to link
#POST {{schema-host-port}}/{{api}}/{{v1}}/migrations/copy
#Content-Type: application/json
#Authorization: Basic {{user_name}} {{passwd}}
#
#{
#  "sourcePool": {{sourcePool}},
#  "targetPools": [{{targetPools}}],
#  "target" : "link"
#}
#
#
#> {%
#    client.test("Response is Internal Server Error, when more targets are specified", function() {
#        client.assert(response.status === 500, "Response status is not 500");
#    });
#%}

### copy endpoint - create request when target attribute set
POST {{schema-host-port}}/{{api}}/{{v1}}/migrations/copy
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

{
  "sourcePool": {{sourcePool}},
  "targetPools": [{{osm_targetPools}}],
  "target" : {{target}}
}


> {%
    client.test("Response is create request", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### copy endpoint - create request with fileAttributes
POST {{schema-host-port}}/{{api}}/{{v1}}/migrations/copy
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

{
  "sourcePool": {{sourcePool}},
  "targetPools": [{{targetPools}}],
  "fileAttributes" : {
      "accessed" : {{accessed}},
      "al" : "online",
      "rp" : "custodial"
  }
}


> {%
    client.test("Response is create request", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}
### GET request to test if response type is json
GET {{schema-host-port}}/{{api}}/{{v1}}/migrations/{{pool_name}}/1
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

> {%
    client.test("Response content-type is json", function() {
        var type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });
%}

### copy endpoint - create request with fileAttributes
POST {{schema-host-port}}/{{api}}/{{v1}}/migrations/copy
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

{
  "sourcePool": {{sourcePool}},
  "targetPools": [{{targetPools}}],
  "fileAttributes" : {
      "al" : "online"
  }
}


> {%
    client.test("Response is create request", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### copy endpoint - create request with fileAttributes
POST {{schema-host-port}}/{{api}}/{{v1}}/migrations/copy
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

{
  "sourcePool": {{sourcePool}},
  "targetPools": [{{targetPools}}],
  "fileAttributes" : {
      "al" : "nearline"
  }
}


> {%
    client.test("Response is create request", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### copy endpoint - create request with fileAttributes
POST {{schema-host-port}}/{{api}}/{{v1}}/migrations/copy
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

{
  "sourcePool": {{sourcePool}},
  "targetPools": [{{targetPools}}],
  "fileAttributes" : {
      "pnfsid" : [{{pnfsid}}]
  }
}


> {%
    client.test("Response is create request", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### copy endpoint - create request with fileAttributes
POST {{schema-host-port}}/{{api}}/{{v1}}/migrations/copy
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

{
  "sourcePool": {{sourcePool}},
  "targetPools": [{{targetPools}}],
  "fileAttributes" : {
      "state" : "cached"
  }
}


> {%
    client.test("Response is crete request", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### copy endpoint - create request with fileAttributes
POST {{schema-host-port}}/{{api}}/{{v1}}/migrations/copy
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

{
  "sourcePool": {{sourcePool}},
  "targetPools": [{{targetPools}}],
  "fileAttributes" : {
      "state" : "precious"
  }
}


> {%
    client.test("Response is create request", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### copy endpoint - create request with fileAttributes
POST {{schema-host-port}}/{{api}}/{{v1}}/migrations/copy
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

{
  "sourcePool": {{sourcePool}},
  "targetPools": [{{targetPools}}],
  "fileAttributes" : {
      "rp" : "custodial"
  }
}

> {%
    client.test("Response is create request", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}


### copy endpoint - create request with fileAttributes
POST {{schema-host-port}}/{{api}}/{{v1}}/migrations/copy
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

{
  "sourcePool": {{sourcePool}},
  "targetPools": [{{targetPools}}],
  "fileAttributes" : {
      "rp" : "replica"
  }
}


> {%
    client.test("Response is create request", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### copy endpoint - create request with fileAttributes
POST {{schema-host-port}}/{{api}}/{{v1}}/migrations/copy
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

{
  "sourcePool": {{sourcePool}},
  "targetPools": [{{targetPools}}],
  "fileAttributes" : {
  "rp" : "output"
  }
}


> {%
    client.test("Response is create request", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### copy endpoint - create request with fileAttributes
POST {{schema-host-port}}/{{api}}/{{v1}}/migrations/copy
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

{
  "sourcePool": {{sourcePool}},
  "targetPools": [{{targetPools}}],
  "fileAttributes" : {
      "size" : {{size}}
  }
}


> {%
    client.test("Response is create request", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### copy endpoint - create request with fileAttributes
POST {{schema-host-port}}/{{api}}/{{v1}}/migrations/copy
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

{
  "sourcePool": {{sourcePool}},
  "targetPools": [{{targetPools}}],
  "fileAttributes" : {
    "sticky" : [{{owners}}]
  }
}

> {%
    client.test("Response is create request", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}



### copy endpoint - create request with fileAttributes
POST {{schema-host-port}}/{{api}}/{{v1}}/migrations/copy
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

{
  "sourcePool": {{sourcePool}},
  "targetPools": [{{targetPools}}],
  "fileAttributes" : {
    "storage" : {{storage}}
  }
}


> {%
    client.test("Response is create request", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

###-----------------migration info tests------------------------------------------------

###  Unsuccessful request to get info from specific job id
GET {{schema-host-port}}/{{api}}/{{v1}}/migrations/{{pool_name}}/2
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

> {%
    client.test("Get migration info", function() {
        client.assert(response.status === 400, "Response status was not 400");
    });
%}

### Unsuccessful request
GET {{schema-host-port}}/{{api}}/{{v1}}/migrations/{{pool_name}}/{{job_id}}
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

> {%
    client.test("Response content-type is json", function() {
        var type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });
%}


### Unsuccessful request
#GET {{schema-host-port}}/{{api}}/{{v1}}/migrations/{{pool_name}}/{{job_id}}
#Content-Type: application/json
#Authorization: Basic {{user_name}} {{passwd}}
#
#> {%
#
#    client.test("Response contains 'state : value' pair", function() {
#        var type = response.body["state"];
#        client.assert(response.body["state"] === "FINISHED", "Expected 'state' to have value 'FINISHED' but received '" + type + "'");
#    });
#%}

### Unsuccessful request
#GET {{schema-host-port}}/{{api}}/{{v1}}/migrations/{{pool_name}}/{{job_id}}
#Content-Type: application/json
#Authorization: Basic {{user_name}} {{passwd}}
#
#> {%
#
#    client.test("Response contains 'queued : value' pair", function() {
#        var type = response.body["queued"];
#        client.assert(response.body["queued"] >= 0, "Expected 'queued' to have value '>=0' but received '" + type + "'");
#    });
#%}

### Unsuccessful request
#GET {{schema-host-port}}/{{api}}/{{v1}}/migrations/{{pool_name}}/{{job_id}}
#Content-Type: application/json
#Authorization: Basic {{user_name}} {{passwd}}
#
#> {%
#
#    client.test("Response contains 'attempts : value' pair", function() {
#        var type = response.body["attempts"];
#        client.assert(response.body["attempts"] >= 1, "Expected 'attempts' to have value '>=1' but received '" + type + "'");
#    });
#%}

### Unsuccessful request
GET {{schema-host-port}}/{{api}}/{{v1}}/migrations/{{pool_name}}/{{job_id}}
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

> {%

    client.test("Response contains 'targetPools : value' pair", function() {
        var type = response.body["targetPools"];
        client.assert(response.body["targetPools"] !== null, "Expected 'targetPools' to have value != null, but received '" + type + "'");
    });
%}

### Unsuccessful request
GET {{schema-host-port}}/{{api}}/{{v1}}/migrations/{{pool_name}}/{{job_id}}
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

> {%

    client.test("Response contains 'completed : value' pair", function() {
        var type = response.body["completed"];
        client.assert(response.body["completed"] !== null, "Expected 'completed' to have value != null, but received '" + type + "'");
    });
%}

### Unsuccessful request
#GET {{schema-host-port}}/{{api}}/{{v1}}/migrations/{{pool_name}}/{{job_id}}
#Content-Type: application/json
#Authorization: Basic {{user_name}} {{passwd}}
#
#> {%
#
#    client.test("Response contains 'total : value' pair", function() {
#        var type = response.body["total"];
#        client.assert(response.body["total"] >= 0, "Expected 'total' to have value '>= 0', but received '" + type + "'");
#    });
#%}

### Unsuccessful request
GET {{schema-host-port}}/{{api}}/{{v1}}/migrations/{{pool_name}}/{{job_id}}
Content-Type: application/json
Authorization: Basic {{user_name}} {{passwd}}

> {%

    client.test("Response contains 'runningTasks : value' pair", function() {
        var type = response.body["runningTasks"];
        client.assert(response.body["runningTasks"] !== null, "Expected 'runningTasks' to have value != null, but received '" + type + "'");
    });
%}