### Generic Tests
### successful qos type:file
GET {{frontend-door}}{{endpoint}}{{qos-management}}/file
accept: application/json
Authorization: Basic {{username}} {{password}}

> {%
    client.test("Successful response for list of quality of services", function() {
        client.assert(response.status === 200, "Expected 200, got " + response.status);
    });
%}

### successful qos type:directory
GET {{frontend-door}}{{endpoint}}{{qos-management}}/directory
accept: application/json
Authorization: Basic {{username}} {{password}}

> {%
    client.test("Successful response for list of quality of services", function() {
        client.assert(response.status === 200, "Expected 200, got " + response.status);
    });
%}

### successful qos file:tape
GET {{frontend-door}}{{endpoint}}{{qos-management}}/file/tape
accept: application/json
Authorization: Basic {{username}} {{password}}

> {%
    client.test("Successful response for tape service", function() {
        client.assert(response.status === 200, "Expected 200, got " + response.status);
    });
%}

### successful qos file:disk
GET {{frontend-door}}{{endpoint}}{{qos-management}}/file/disk
accept: application/json
Authorization: Basic {{username}} {{password}}

> {%
    client.test("Successful response for disk service", function() {
        client.assert(response.status === 200, "Expected 200, got " + response.status);
    });
%}


### successful qos file:disk+tape
GET {{frontend-door}}{{endpoint}}{{qos-management}}/file/disk+tape
accept: application/json
Authorization: Basic {{username}} {{password}}

> {%
    client.test("Successful response for disk+tape service", function() {
        client.assert(response.status === 200, "Expected 200, got " + response.status);
    });
%}

### successful qos file:volatile
GET {{frontend-door}}{{endpoint}}{{qos-management}}/file/volatile
accept: application/json
Authorization: Basic {{username}} {{password}}

> {%
    client.test("Successful response for volatile service", function() {
        client.assert(response.status === 200, "Expected 200, got " + response.status);
    });
%}


### Not defined QoS
GET {{frontend-door}}{{endpoint}}{{qos-management}}/file/test
accept: application/json
Authorization: Basic {{username}} {{password}}

> {%
    client.test("qos requested does not exist", function() {
        client.assert(response.status === 400, "Expected 400, got " + response.status);
    });
%}

### Incorrect basic authentication credentials
GET {{frontend-door}}{{endpoint}}{{qos-management}}/file/test
accept: application/json
Authorization: Basic {{username}} {{incorrect_password}}

> {%
    client.test("Incorrect basic authentication credentials ", function() {
        client.assert(response.status === 401, "Expected 401, got " + response.status);
    });
%}


### successful qos directoy:tape
GET {{frontend-door}}{{endpoint}}{{qos-management}}/directory/tape
accept: application/json
Authorization: Basic {{username}} {{password}}

> {%
    client.test("Successful response for tape service", function() {
        client.assert(response.status === 200, "Expected 200, got " + response.status);
    });
%}

### successful qos directoy:disk
GET {{frontend-door}}{{endpoint}}{{qos-management}}/directory/disk
accept: application/json
Authorization: Basic {{username}} {{password}}

> {%
    client.test("Successful response for disk service", function() {
        client.assert(response.status === 200, "Expected 200, got " + response.status);
    });
%}


### successful qos directoy:disk+tape
GET {{frontend-door}}{{endpoint}}{{qos-management}}/directory/disk+tape
accept: application/json
Authorization: Basic {{username}} {{password}}

> {%
    client.test("Successful response for disk+tape service", function() {
        client.assert(response.status === 200, "Expected 200, got " + response.status);
    });
%}

### successful qos directoy:volatile
GET {{frontend-door}}{{endpoint}}{{qos-management}}/directory/volatile
accept: application/json
Authorization: Basic {{username}} {{password}}

> {%
    client.test("Successful response for volatile service", function() {
        client.assert(response.status === 200, "Expected 200, got " + response.status);
    });
%}