/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;
/**
 * Enumeration (collection of constants).
 */
public interface channel_dir_from_server4 {

    public static final int CDFS4_FORE = 0x1;
    public static final int CDFS4_BACK = 0x2;
    public static final int CDFS4_BOTH = 0x3;

}
// End of channel_dir_from_server4.java
