/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;
import org.dcache.xdr.*;
import java.io.IOException;

public class createhow4 implements XdrAble {
    public int mode;
    public fattr4 createattrs;
    public verifier4 createverf;
    public creatverfattr ch_createboth;

    public createhow4() {
    }

    public createhow4(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeInt(mode);
        switch ( mode ) {
        case createmode4.UNCHECKED4:
        case createmode4.GUARDED4:
            createattrs.xdrEncode(xdr);
            break;
        case createmode4.EXCLUSIVE4:
            createverf.xdrEncode(xdr);
            break;
        case createmode4.EXCLUSIVE4_1:
            ch_createboth.xdrEncode(xdr);
            break;
        }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        mode = xdr.xdrDecodeInt();
        switch ( mode ) {
        case createmode4.UNCHECKED4:
        case createmode4.GUARDED4:
            createattrs = new fattr4(xdr);
            break;
        case createmode4.EXCLUSIVE4:
            createverf = new verifier4(xdr);
            break;
        case createmode4.EXCLUSIVE4_1:
            ch_createboth = new creatverfattr(xdr);
            break;
        }
    }

}
// End of createhow4.java
