/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;
/**
 * Enumeration (collection of constants).
 */
public interface filelayout_hint_care4 {

    public static final int NFLH4_CARE_DENSE = nfs4_prot.NFL4_UFLG_DENSE;
    public static final int NFLH4_CARE_COMMIT_THRU_MDS = nfs4_prot.NFL4_UFLG_COMMIT_THRU_MDS;
    public static final int NFLH4_CARE_STRIPE_UNIT_SIZE = 0x00000040;
    public static final int NFLH4_CARE_STRIPE_COUNT = 0x00000080;

}
// End of filelayout_hint_care4.java
