/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;
/**
 * Enumeration (collection of constants).
 */
public interface layoutiomode4 {

    public static final int LAYOUTIOMODE4_READ = 1;
    public static final int LAYOUTIOMODE4_RW = 2;
    public static final int LAYOUTIOMODE4_ANY = 3;

}
// End of layoutiomode4.java
