/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;
import java.util.Arrays;
import org.dcache.xdr.*;
import java.io.IOException;

public class sessionid4 implements XdrAble {

    public byte [] value;

    public sessionid4() {
    }

    public sessionid4(byte [] value) {
        this.value = value;
    }

    public sessionid4(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeOpaque(value, nfs4_prot.NFS4_SESSIONID_SIZE);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        value = xdr.xdrDecodeOpaque(nfs4_prot.NFS4_SESSIONID_SIZE);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this)  return true;
        if ( !(obj instanceof sessionid4 )) return false;

        final sessionid4 other = (sessionid4) obj;

        return Arrays.equals(this.value, other.value);
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 23 * hash + Arrays.hashCode(this.value);
        return hash;
    }

    @Override
    public String toString() {
        return new String(value);
    }
}
// End of sessionid4.java
