/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;
import org.dcache.chimera.nfs.v4.*;
import org.dcache.xdr.*;
import java.io.IOException;

public class SETCLIENTID4res implements XdrAble {
    public int status;
    public SETCLIENTID4resok resok4;
    public clientaddr4 client_using;

    public SETCLIENTID4res() {
    }

    public SETCLIENTID4res(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeInt(status);
        switch ( status ) {
        case nfsstat4.NFS4_OK:
            resok4.xdrEncode(xdr);
            break;
        case nfsstat4.NFS4ERR_CLID_INUSE:
            client_using.xdrEncode(xdr);
            break;
        default:
            break;
        }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        status = xdr.xdrDecodeInt();
        switch ( status ) {
        case nfsstat4.NFS4_OK:
            resok4 = new SETCLIENTID4resok(xdr);
            break;
        case nfsstat4.NFS4ERR_CLID_INUSE:
            client_using = new clientaddr4(xdr);
            break;
        default:
            break;
        }
    }

}
// End of SETCLIENTID4res.java
