/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;
import org.dcache.xdr.*;
import java.io.IOException;

public class specdata4 implements XdrAble {
    public uint32_t specdata1;
    public uint32_t specdata2;

    public specdata4() {
    }

    public specdata4(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        specdata1.xdrEncode(xdr);
        specdata2.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        specdata1 = new uint32_t(xdr);
        specdata2 = new uint32_t(xdr);
    }

}
// End of specdata4.java
