/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;
/**
 * Enumeration (collection of constants).
 */
public interface time_how4 {

    public static final int SET_TO_SERVER_TIME4 = 0;
    public static final int SET_TO_CLIENT_TIME4 = 1;

}
// End of time_how4.java
