// generated by GLUE/wsdl2java on Thu Jan 13 10:36:54 CST 2005
package diskCacheV111.srm;

import java.io.Serializable;
import java.util.Date;

public class RequestStatus implements Serializable
  {
    private static final long serialVersionUID = -7407954557920586704L;
    public  transient static final String EMPTY="";
  public int requestId;
    public String type =EMPTY;
    public String state=EMPTY;
    public Date submitTime=new Date();
    public Date startTime = new Date();
    public Date finishTime = new Date();
  public int estTimeToStart;
    public RequestFileStatus[] fileStatuses = new RequestFileStatus[0];
    public String errorMessage = EMPTY;
  public int retryDeltaTime;
  
   public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("RequestStatus      requestId :").
        append(requestId).append('\n');
        sb.append("                   type :")
        .append(type).append('\n');
        sb.append("                   state :")
        .append(state).append('\n');
        sb.append("                   submitTime :")
        .append(submitTime).append('\n');
        sb.append("                   startTime :")
        .append(startTime).append('\n');
        sb.append("                   finishTime :")
        .append(finishTime).append('\n');
        sb.append("                   estTimeToStart :")
        .append(estTimeToStart).append('\n');
        int len=fileStatuses.length;
        for(int i= 0; i<len;++i) {
            sb.append("                   fileStatuses#")
            .append(i).append(" :").append(fileStatuses[i]).append('\n');
        }
        sb.append("                   estTimeToStart :")
        .append(estTimeToStart).append('\n');
        sb.append("                   errorMessage :")
        .append(errorMessage).append('\n');
        sb.append("                   retryDeltaTime :")
        .append(retryDeltaTime).append('\n');
        return sb.toString();
    }
  }
