#!/bin/sh -f
#
# @(#) $Id: dclist,v 1.3 2003-10-20 15:25:31 cvs Exp $
#
# $Log: not supported by cvs2svn $
# Revision 1.2  2003/05/09 18:33:49  cvs
# modified script by putting "$@" instead of $@ so that the parametes with spaces are not expanded
#
# Revision 1.1  2003/04/10 22:04:18  cvs
# dcache authorization file management scripts added
#
# Revision 1.5  2003/02/10 22:03:15  cvs
# not always on home
#
# Revision 1.4  2002/09/04 15:52:15  cvs
# path and password name change
#
# Revision 1.3  2002/07/18 00:41:01  cvs
# move the password file from orphan directory etc into config
#
# Revision 1.2  2002/06/28 00:30:23  cvs
# preliminary gsi/mode E support
#
# Revision 1.1  2002/02/20 23:37:36  cvs
# Added scripts directory and scripts needed for enstore interaction
#
# Revision 1.1  2001/09/20 02:43:02  ivm
# Initial CVS deposit
#
#


node=`uname -n| sed -e 's/\([^\.]\)\..*/\1/'`

if [ -r /usr/local/bin/ENSTORE_HOME ]; then
   . /usr/local/bin/ENSTORE_HOME
    top=$E_H/dcache-deploy
else
   top=/opt/d-cache
fi

etc=${top}/etc 
pwdfile=${etc}/dcache.kpwd
CLASSPATH=${top}/classes/dcache.jar
command=`basename "$0"`
$JAVA_HOME/bin/java -cp $CLASSPATH diskCacheV111.util.KAuthFile $command ${pwdfile} "$@"

 
