#!/bin/sh
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

. ~enstore/dcache-deploy/config/dCacheSetup

set -u  

routes=/tmp/dcache.routes
output=~enstore/tomcat/latest/webapps/ROOT/dcache.ping.html
toutput=/tmp/ping.dcache.html
dt=/tmp/dt
pt=/tmp/pt

badfnt=\"#000066\"
goodfnt=\"#006600\"
badfnt=\"#660000\"

rm -f $routes >/dev/null 2>/dev/null

cmd="exit
set dest RoutingMgr@dCacheDomain
info
exit
exit"
echo RoutingMgr@dCacheDomain ssh -c blowfish -p $sshPort $serviceLocatorHost
echo "$cmd" | ssh -c blowfish -p $sshPort $serviceLocatorHost >$routes 2>&1


export oldIFS="$IFS"
IFS="
"
cat $routes  | tr -d "\r" | while read line; do
 export domain=`echo $line | cut -f1 -d: | sed -e 's/ //g'`
 if [ `echo $domain | grep -ic door` -ne 0 ]; then
    chk=DCAP`echo $domain | sed -e 's/door//' -e 's/Domain//'`
 else
    chk=""
 fi
 export cells="$chk "`echo $line | cut -f2 -d: | sed -e 's/,/ /g'`
 cells=${cells:-System}
 if [ $domain = "Local" ]; then domain=dCacheDomain; fi
 if [ `echo $domain | grep -ic domain` -eq 0 -o `echo $domain | grep -ic Routing` -ne 0 ]; then continue; fi
 ( IFS="$oldIFS"
   for cell in $cells; do
     cell=`echo $cell | sed -e 's/ //g'`
     cmd="exit
set dest System@dCacheDomain
ping $cell@$domain
exit
exit"
     rm -f $dt
     echo `date` $cell@$domain
     /usr/bin/time -o $dt -f '%e' echo "$cmd" | ssh -c blowfish -p $sshPort $serviceLocatorHost 2>/dev/null | tr -d "\r" > $pt 2>&1
     pcnt=`grep -c Done $pt`
     if [ $pcnt -eq 1 ]; then 
	ok='OK '
	fnt="$goodfnt"
	real=`cat $dt`
	rm -f /tmp/dcache.ping.$cell.$domain >/dev/null 2>/dev/null
     else 
	ok=`cat $pt`
	fnt="$badfnt"
	real=""
        echo "<tr> <td align="Left" nosave=""><b><font color=$fnt size="+2"> $cell@$domain </td> <td valign="CENTER" nosave=""><font color=$fnt size="+2">  $ok </td> <td align="Left" nosave=""><b><font color=$fnt size="+2"> $real </td> <td align="Left" nosave=""><b><font color=$fnt size="+2"> `date` </td> </tr> " > /tmp/dcache.ping.$cell.$domain
 
     fi
     echo  `date` $cell@$domain $ok $real
   done )
   rm -f $toutput
   echo "<html><head><title>DCA Data Cache Ping</title></head>" >> $toutput
   echo '<body text=$goodfnt bgcolor="#ffffff" link="#0000ef" vlink="#55188a" alink="#ff0000" background="enstore.gif">' >> $toutput
   echo '<table border="1" width="80%" bgcolor="#dff0ff" nosave="" cellspacing="5" cellpadding="2"> <tbody>' >> $toutput
   echo "<tr> <td align="Left" nosave=""><b><font color=$goodfnt size="+2">  cell@domain </td> <td valign="CENTER" nosave=""><font color=$goodfnt size="+2"> Status </td> <td align="Left" nosave=""><b><font color=$goodfnt size="+2"> Ping time </td> <td align="Left" nosave=""><b><font color=$goodfnt size="+2">   `date` </td> </tr> " >> $toutput
   echo "<tr> <td>              </td> <td>        </td> <td>           </td> <td>      </td> </tr> " >> $toutput
   cat /tmp/dcache.ping* >> $toutput 2>/dev/null
   echo '</tbody></table></body></html>' >> $toutput
   cp $toutput $output
done

IFS="$oldIFS"
