# to descend to directories, construct
# the list of directories apending '_target'
# and inserting Makefile in each directory.
SRM_PATH=../..
PACKAGE=gov.fnal
include $(SRM_PATH)/conf/ostype.inc

TARGETS = 		\
  srm_target \
  

MAKE_TARGETS = $(TARGETS:_target=_make)

include $(SRM_PATH)/conf/config.inc


