#
# $Id: Makefile.alpha,v 1.11 2003-08-19 08:53:48 tigran Exp $
#

#
# Makefile for DEC Alpha
#

#CC = 
CFLAGS = -g -I. -DNOT_THREAD_SAFE -std1 -DBSD_SYSCALLS

MAKEDEP = $(CC) -M

SO_EXT = .so
A_EXT = .a
EXE_EXT =

RANLIB = ranlib
ARFLAGS = rv


# for gcc

#CC = gcc
#CFLAGS = -g -O0 -D_REENTRANT

LIBS = -lc
LDFLAGS = -shared

include Makefile.inc
