#!/bin/zsh

DEST=/pnfs/fs/usr/dmg/eagle/tigran/bigfile
SOURCE=bigfile
ELOG=$0.log

if [ $# -ne "1" ]
then
	exit 1
fi

echo "Starting the Writer Test"
rm -f $ELOG
touch $ELOG
(

i=0

while (test $i -lt $1)
do
	dccp $SOURCE $DEST.1$i 2>>$ELOG &
	i=`expr $i + 1`
done

wait
) | report.awk

echo "Test Done! Check for errors in $ELOG"
