/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;
import org.dcache.xdr.*;
import java.io.IOException;

public class CB_WANTS_CANCELLED4args implements XdrAble {
    public boolean cwca_contended_wants_cancelled;
    public boolean cwca_resourced_wants_cancelled;

    public CB_WANTS_CANCELLED4args() {
    }

    public CB_WANTS_CANCELLED4args(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeBoolean(cwca_contended_wants_cancelled);
        xdr.xdrEncodeBoolean(cwca_resourced_wants_cancelled);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        cwca_contended_wants_cancelled = xdr.xdrDecodeBoolean();
        cwca_resourced_wants_cancelled = xdr.xdrDecodeBoolean();
    }

}
// End of CB_WANTS_CANCELLED4args.java
