/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;
import org.dcache.xdr.*;
import java.io.IOException;

public class change_policy4 implements XdrAble {
    public uint64_t cp_major;
    public uint64_t cp_minor;

    public change_policy4() {
    }

    public change_policy4(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        cp_major.xdrEncode(xdr);
        cp_minor.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        cp_major = new uint64_t(xdr);
        cp_minor = new uint64_t(xdr);
    }

}
// End of change_policy4.java
