/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;
import org.dcache.xdr.*;
import java.io.IOException;

public class creatverfattr implements XdrAble {
    public verifier4 cva_verf;
    public fattr4 cva_attrs;

    public creatverfattr() {
    }

    public creatverfattr(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        cva_verf.xdrEncode(xdr);
        cva_attrs.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        cva_verf = new verifier4(xdr);
        cva_attrs = new fattr4(xdr);
    }

}
// End of creatverfattr.java
