/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;
import org.dcache.xdr.*;
import java.io.IOException;

public class fattr4_suppattr_exclcreat implements XdrAble {

    public bitmap4 value;

    public fattr4_suppattr_exclcreat() {
    }

    public fattr4_suppattr_exclcreat(bitmap4 value) {
        this.value = value;
    }

    public fattr4_suppattr_exclcreat(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        value.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        value = new bitmap4(xdr);
    }

}
// End of fattr4_suppattr_exclcreat.java
