/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;
import org.dcache.xdr.*;
import java.io.IOException;

public class fattr4_mode_set_masked implements XdrAble {

    public mode_masked4 value;

    public fattr4_mode_set_masked() {
    }

    public fattr4_mode_set_masked(mode_masked4 value) {
        this.value = value;
    }

    public fattr4_mode_set_masked(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        value.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        value = new mode_masked4(xdr);
    }

}
// End of fattr4_mode_set_masked.java
