/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;
import org.dcache.chimera.nfs.v4.*;
import org.dcache.xdr.*;
import java.io.IOException;

public class GET_DIR_DELEGATION4resok implements XdrAble {
    public verifier4 gddr_cookieverf;
    public stateid4 gddr_stateid;
    public bitmap4 gddr_notification;
    public bitmap4 gddr_child_attributes;
    public bitmap4 gddr_dir_attributes;

    public GET_DIR_DELEGATION4resok() {
    }

    public GET_DIR_DELEGATION4resok(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        gddr_cookieverf.xdrEncode(xdr);
        gddr_stateid.xdrEncode(xdr);
        gddr_notification.xdrEncode(xdr);
        gddr_child_attributes.xdrEncode(xdr);
        gddr_dir_attributes.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        gddr_cookieverf = new verifier4(xdr);
        gddr_stateid = new stateid4(xdr);
        gddr_notification = new bitmap4(xdr);
        gddr_child_attributes = new bitmap4(xdr);
        gddr_dir_attributes = new bitmap4(xdr);
    }

}
// End of GET_DIR_DELEGATION4resok.java
