/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;
/**
 * Enumeration (collection of constants).
 */
public interface layoutrecall_type4 {

    public static final int LAYOUTRECALL4_FILE = nfs4_prot.LAYOUT4_RET_REC_FILE;
    public static final int LAYOUTRECALL4_FSID = nfs4_prot.LAYOUT4_RET_REC_FSID;
    public static final int LAYOUTRECALL4_ALL = nfs4_prot.LAYOUT4_RET_REC_ALL;

}
// End of layoutrecall_type4.java
