/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;
import org.dcache.chimera.nfs.v4.*;
import org.dcache.xdr.*;
import java.io.IOException;

public class LAYOUTGET4resok implements XdrAble {
    public boolean logr_return_on_close;
    public stateid4 logr_stateid;
    public layout4 [] logr_layout;

    public LAYOUTGET4resok() {
    }

    public LAYOUTGET4resok(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeBoolean(logr_return_on_close);
        logr_stateid.xdrEncode(xdr);
        { int $size = logr_layout.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { logr_layout[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        logr_return_on_close = xdr.xdrDecodeBoolean();
        logr_stateid = new stateid4(xdr);
        { int $size = xdr.xdrDecodeInt(); logr_layout = new layout4[$size]; for ( int $idx = 0; $idx < $size; ++$idx ) { logr_layout[$idx] = new layout4(xdr); } }
    }

}
// End of LAYOUTGET4resok.java
