/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;
import org.dcache.xdr.*;
import java.io.IOException;

public class netaddr4 implements XdrAble {
    public String na_r_netid;
    public String na_r_addr;

    public netaddr4() {
    }

    public netaddr4(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeString(na_r_netid);
        xdr.xdrEncodeString(na_r_addr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        na_r_netid = xdr.xdrDecodeString();
        na_r_addr = xdr.xdrDecodeString();
    }

}
// End of netaddr4.java
