/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;
/**
 * Enumeration (collection of constants).
 */
public interface notify_deviceid_type4 {

    public static final int NOTIFY_DEVICEID4_CHANGE = 1;
    public static final int NOTIFY_DEVICEID4_DELETE = 2;

}
// End of notify_deviceid_type4.java
