/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;
/**
 * Enumeration (collection of constants).
 */
public interface notify_type4 {

    public static final int NOTIFY4_CHANGE_CHILD_ATTRS = 0;
    public static final int NOTIFY4_CHANGE_DIR_ATTRS = 1;
    public static final int NOTIFY4_REMOVE_ENTRY = 2;
    public static final int NOTIFY4_ADD_ENTRY = 3;
    public static final int NOTIFY4_RENAME_ENTRY = 4;
    public static final int NOTIFY4_CHANGE_COOKIE_VERIFIER = 5;

}
// End of notify_type4.java
