/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;
import org.dcache.xdr.*;
import java.io.IOException;

public class referring_call4 implements XdrAble {
    public sequenceid4 rc_sequenceid;
    public slotid4 rc_slotid;

    public referring_call4() {
    }

    public referring_call4(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        rc_sequenceid.xdrEncode(xdr);
        rc_slotid.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        rc_sequenceid = new sequenceid4(xdr);
        rc_slotid = new slotid4(xdr);
    }

}
// End of referring_call4.java
