/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;
import org.dcache.xdr.*;
import java.io.IOException;

public class SECINFO_NO_NAME4res implements XdrAble {

    public SECINFO4res value;

    public SECINFO_NO_NAME4res() {
    }

    public SECINFO_NO_NAME4res(SECINFO4res value) {
        this.value = value;
    }

    public SECINFO_NO_NAME4res(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        value.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        value = new SECINFO4res(xdr);
    }

}
// End of SECINFO_NO_NAME4res.java
