/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;
/**
 * Enumeration (collection of constants).
 */
public interface ssv_subkey4 {

    public static final int SSV4_SUBKEY_MIC_I2T = 1;
    public static final int SSV4_SUBKEY_MIC_T2I = 2;
    public static final int SSV4_SUBKEY_SEAL_I2T = 3;
    public static final int SSV4_SUBKEY_SEAL_T2I = 4;

}
// End of ssv_subkey4.java
