/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;
/**
 * Enumeration (collection of constants).
 */
public interface stable_how4 {

    public static final int UNSTABLE4 = 0;
    public static final int DATA_SYNC4 = 1;
    public static final int FILE_SYNC4 = 2;

}
// End of stable_how4.java
