#!/bin/sh
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

# this is cheap argument processing. Must be in this order when checking. I want it cheap!
if [ "${1:-}" = "-d" ] ; then doorlist=~enstore/dcache-deploy/config/door*$2*.batch; shift; shift; fi
echo $doorlist
command=${1:-info}

. ~enstore/dcache-deploy/config/dCacheSetup

doorlist=~enstore/dcache-deploy/config/door*.batch

oldIFS="$IFS"
IFS="
"
for line in $doorlist;do
  basename=`basename $line`
  door=`echo $basename | sed -e 's/.batch//' -e 's/door//'`
  cmd="exit
set dest DCap${door}@door${door}Domain
$command
exit
exit"
   echo DCap${door}@door${door}Domain: ssh -c blowfish -p $sshPort $serviceLocatorHost
   echo "$cmd" | ssh -c blowfish -p $sshPort $serviceLocatorHost  2>/dev/null
done
IFS="$oldIFS"

