/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;

import java.io.IOException;

import org.dcache.xdr.OncRpcException;
import org.dcache.xdr.XdrAble;
import org.dcache.xdr.XdrDecodingStream;
import org.dcache.xdr.XdrEncodingStream;

public class CB_LAYOUTRECALL4args implements XdrAble {
    public int clora_type;
    public int clora_iomode;
    public boolean clora_changed;
    public layoutrecall4 clora_recall;

    public CB_LAYOUTRECALL4args() {
    }

    public CB_LAYOUTRECALL4args(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    @Override
    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeInt(clora_type);
        xdr.xdrEncodeInt(clora_iomode);
        xdr.xdrEncodeBoolean(clora_changed);
        clora_recall.xdrEncode(xdr);
    }

    @Override
    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        clora_type = xdr.xdrDecodeInt();
        clora_iomode = xdr.xdrDecodeInt();
        clora_changed = xdr.xdrDecodeBoolean();
        clora_recall = new layoutrecall4(xdr);
    }

}
// End of CB_LAYOUTRECALL4args.java
