/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;
import org.dcache.chimera.nfs.v4.*;
import org.dcache.xdr.*;
import java.io.IOException;

public class CB_PUSH_DELEG4args implements XdrAble {
    public nfs_fh4 cpda_fh;
    public open_delegation4 cpda_delegation;

    public CB_PUSH_DELEG4args() {
    }

    public CB_PUSH_DELEG4args(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    @Override
    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        cpda_fh.xdrEncode(xdr);
        cpda_delegation.xdrEncode(xdr);
    }

    @Override
    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        cpda_fh = new nfs_fh4(xdr);
        cpda_delegation = new open_delegation4(xdr);
    }

}
// End of CB_PUSH_DELEG4args.java
