/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;
import org.dcache.chimera.nfs.v4.*;
import org.dcache.xdr.*;
import java.io.IOException;

public class CB_RECALL4args implements XdrAble {
    public stateid4 stateid;
    public boolean truncate;
    public nfs_fh4 fh;

    public CB_RECALL4args() {
    }

    public CB_RECALL4args(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    @Override
    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        stateid.xdrEncode(xdr);
        xdr.xdrEncodeBoolean(truncate);
        fh.xdrEncode(xdr);
    }

    @Override
    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        stateid = new stateid4(xdr);
        truncate = xdr.xdrDecodeBoolean();
        fh = new nfs_fh4(xdr);
    }

}
// End of CB_RECALL4args.java
