/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;

import java.io.IOException;

import org.dcache.xdr.OncRpcException;
import org.dcache.xdr.XdrAble;
import org.dcache.xdr.XdrDecodingStream;
import org.dcache.xdr.XdrEncodingStream;

public class CB_RECALLABLE_OBJ_AVAIL4args implements XdrAble {

    public CB_RECALL_ANY4args value;

    public CB_RECALLABLE_OBJ_AVAIL4args() {
    }

    public CB_RECALLABLE_OBJ_AVAIL4args(CB_RECALL_ANY4args value) {
        this.value = value;
    }

    public CB_RECALLABLE_OBJ_AVAIL4args(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    @Override
    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        value.xdrEncode(xdr);
    }

    @Override
    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        value = new CB_RECALL_ANY4args(xdr);
    }

}
// End of CB_RECALLABLE_OBJ_AVAIL4args.java
