/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;

import java.io.IOException;

import org.dcache.chimera.nfs.nfsstat;
import org.dcache.xdr.OncRpcException;
import org.dcache.xdr.XdrAble;
import org.dcache.xdr.XdrDecodingStream;
import org.dcache.xdr.XdrEncodingStream;

public class EXCHANGE_ID4res implements XdrAble {
    public int eir_status;
    public EXCHANGE_ID4resok eir_resok4;

    public EXCHANGE_ID4res() {
    }

    public EXCHANGE_ID4res(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    @Override
    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeInt(eir_status);
        switch ( eir_status ) {
        case nfsstat.NFS_OK:
            eir_resok4.xdrEncode(xdr);
            break;
        default:
            break;
        }
    }

    @Override
    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        eir_status = xdr.xdrDecodeInt();
        switch ( eir_status ) {
        case nfsstat.NFS_OK:
            eir_resok4 = new EXCHANGE_ID4resok(xdr);
            break;
        default:
            break;
        }
    }

}
// End of EXCHANGE_ID4res.java
