/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;

import java.io.IOException;

import org.dcache.xdr.OncRpcException;
import org.dcache.xdr.XdrAble;
import org.dcache.xdr.XdrDecodingStream;
import org.dcache.xdr.XdrEncodingStream;

public class fs_locations_server4 implements XdrAble {
    public int32_t fls_currency;
    public byte [] fls_info;
    public utf8str_cis fls_server;

    public fs_locations_server4() {
    }

    public fs_locations_server4(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    @Override
    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        fls_currency.xdrEncode(xdr);
        xdr.xdrEncodeDynamicOpaque(fls_info);
        fls_server.xdrEncode(xdr);
    }

    @Override
    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        fls_currency = new int32_t(xdr);
        fls_info = xdr.xdrDecodeDynamicOpaque();
        fls_server = new utf8str_cis(xdr);
    }

}
// End of fs_locations_server4.java
