/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;
import org.dcache.xdr.*;
import java.io.IOException;

public class fs_location4 implements XdrAble {
    public utf8str_cis [] server;
    public pathname4 rootpath;

    public fs_location4() {
    }

    public fs_location4(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    @Override
    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        { int $size = server.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { server[$idx].xdrEncode(xdr); } }
        rootpath.xdrEncode(xdr);
    }

    @Override
    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        { int $size = xdr.xdrDecodeInt(); server = new utf8str_cis[$size]; for ( int $idx = 0; $idx < $size; ++$idx ) { server[$idx] = new utf8str_cis(xdr); } }
        rootpath = new pathname4(xdr);
    }

}
// End of fs_location4.java
