/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;

import java.io.IOException;

import org.dcache.xdr.OncRpcException;
import org.dcache.xdr.XdrAble;
import org.dcache.xdr.XdrDecodingStream;
import org.dcache.xdr.XdrEncodingStream;

public class LAYOUTRETURN4args implements XdrAble {
    public boolean lora_reclaim;
    public int lora_layout_type;
    public int lora_iomode;
    public layoutreturn4 lora_layoutreturn;

    public LAYOUTRETURN4args() {
    }

    public LAYOUTRETURN4args(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    @Override
    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeBoolean(lora_reclaim);
        xdr.xdrEncodeInt(lora_layout_type);
        xdr.xdrEncodeInt(lora_iomode);
        lora_layoutreturn.xdrEncode(xdr);
    }

    @Override
    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        lora_reclaim = xdr.xdrDecodeBoolean();
        lora_layout_type = xdr.xdrDecodeInt();
        lora_iomode = xdr.xdrDecodeInt();
        lora_layoutreturn = new layoutreturn4(xdr);
    }

}
// End of LAYOUTRETURN4args.java
