/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;

import java.io.IOException;

import org.dcache.xdr.OncRpcException;
import org.dcache.xdr.XdrAble;
import org.dcache.xdr.XdrDecodingStream;
import org.dcache.xdr.XdrEncodingStream;

public class LAYOUTCOMMIT4args implements XdrAble {
    public offset4 loca_offset;
    public length4 loca_length;
    public boolean loca_reclaim;
    public stateid4 loca_stateid;
    public newoffset4 loca_last_write_offset;
    public newtime4 loca_time_modify;
    public layoutupdate4 loca_layoutupdate;

    public LAYOUTCOMMIT4args() {
    }

    public LAYOUTCOMMIT4args(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    @Override
    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        loca_offset.xdrEncode(xdr);
        loca_length.xdrEncode(xdr);
        xdr.xdrEncodeBoolean(loca_reclaim);
        loca_stateid.xdrEncode(xdr);
        loca_last_write_offset.xdrEncode(xdr);
        loca_time_modify.xdrEncode(xdr);
        loca_layoutupdate.xdrEncode(xdr);
    }

    @Override
    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        loca_offset = new offset4(xdr);
        loca_length = new length4(xdr);
        loca_reclaim = xdr.xdrDecodeBoolean();
        loca_stateid = new stateid4(xdr);
        loca_last_write_offset = new newoffset4(xdr);
        loca_time_modify = new newtime4(xdr);
        loca_layoutupdate = new layoutupdate4(xdr);
    }

}
// End of LAYOUTCOMMIT4args.java
