/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;
import org.dcache.xdr.*;
import java.io.IOException;

public class layoutreturn_stateid implements XdrAble {
    public boolean lrs_present;
    public stateid4 lrs_stateid;

    public layoutreturn_stateid() {
    }

    public layoutreturn_stateid(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeBoolean(lrs_present);
        if ( lrs_present ) {
            lrs_stateid.xdrEncode(xdr);
        }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        lrs_present = xdr.xdrDecodeBoolean();
        if ( lrs_present ) {
            lrs_stateid = new stateid4(xdr);
        }
    }

}
// End of layoutreturn_stateid.java
