/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;

import java.io.IOException;

import org.dcache.xdr.OncRpcException;
import org.dcache.xdr.XdrAble;
import org.dcache.xdr.XdrDecodingStream;
import org.dcache.xdr.XdrEncodingStream;

public class layout4 implements XdrAble {
    public offset4 lo_offset;
    public length4 lo_length;
    public int lo_iomode;
    public layout_content4 lo_content;

    public layout4() {
    }

    public layout4(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    @Override
    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        lo_offset.xdrEncode(xdr);
        lo_length.xdrEncode(xdr);
        xdr.xdrEncodeInt(lo_iomode);
        lo_content.xdrEncode(xdr);
    }

    @Override
    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        lo_offset = new offset4(xdr);
        lo_length = new length4(xdr);
        lo_iomode = xdr.xdrDecodeInt();
        lo_content = new layout_content4(xdr);
    }

}
// End of layout4.java
