/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;
import org.dcache.chimera.nfs.nfsstat;
import org.dcache.chimera.nfs.v4.*;
import org.dcache.xdr.*;
import java.io.IOException;

public class LOCK4res implements XdrAble {
    public int status;
    public LOCK4resok resok4;
    public LOCK4denied denied;

    public LOCK4res() {
    }

    public LOCK4res(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeInt(status);
        switch ( status ) {
        case nfsstat.NFS_OK:
            resok4.xdrEncode(xdr);
            break;
        case nfsstat.NFSERR_DENIED:
            denied.xdrEncode(xdr);
            break;
        default:
            break;
        }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        status = xdr.xdrDecodeInt();
        switch ( status ) {
        case nfsstat.NFS_OK:
            resok4 = new LOCK4resok(xdr);
            break;
        case nfsstat.NFSERR_DENIED:
            denied = new LOCK4denied(xdr);
            break;
        default:
            break;
        }
    }

}
// End of LOCK4res.java
