/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;
import org.dcache.xdr.*;
import java.io.IOException;

public class newoffset4 implements XdrAble {
    public boolean no_newoffset;
    public offset4 no_offset;

    public newoffset4() {
    }

    public newoffset4(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeBoolean(no_newoffset);
        if ( no_newoffset ) {
            no_offset.xdrEncode(xdr);
        }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        no_newoffset = xdr.xdrDecodeBoolean();
        if ( no_newoffset ) {
            no_offset = new offset4(xdr);
        }
    }

}
// End of newoffset4.java
