/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;

import java.io.IOException;

import org.dcache.xdr.OncRpcException;
import org.dcache.xdr.XdrAble;
import org.dcache.xdr.XdrDecodingStream;
import org.dcache.xdr.XdrEncodingStream;

public class nfsacl41 implements XdrAble {
    public aclflag4 na41_flag;
    public nfsace4 [] na41_aces;

    public nfsacl41() {
    }

    public nfsacl41(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    @Override
    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        na41_flag.xdrEncode(xdr);
        { int $size = na41_aces.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { na41_aces[$idx].xdrEncode(xdr); } }
    }

    @Override
    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        na41_flag = new aclflag4(xdr);
        { int $size = xdr.xdrDecodeInt(); na41_aces = new nfsace4[$size]; for ( int $idx = 0; $idx < $size; ++$idx ) { na41_aces[$idx] = new nfsace4(xdr); } }
    }

}
// End of nfsacl41.java
