/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;

import java.io.IOException;

import org.dcache.xdr.OncRpcException;
import org.dcache.xdr.XdrAble;
import org.dcache.xdr.XdrDecodingStream;
import org.dcache.xdr.XdrEncodingStream;

public class notify_verifier4 implements XdrAble {
    public verifier4 nv_old_cookieverf;
    public verifier4 nv_new_cookieverf;

    public notify_verifier4() {
    }

    public notify_verifier4(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    @Override
    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        nv_old_cookieverf.xdrEncode(xdr);
        nv_new_cookieverf.xdrEncode(xdr);
    }

    @Override
    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        nv_old_cookieverf = new verifier4(xdr);
        nv_new_cookieverf = new verifier4(xdr);
    }

}
// End of notify_verifier4.java
