/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;

import java.io.IOException;

import org.dcache.xdr.OncRpcException;
import org.dcache.xdr.XdrAble;
import org.dcache.xdr.XdrDecodingStream;
import org.dcache.xdr.XdrEncodingStream;

public class open_delegation4 implements XdrAble {
    public int delegation_type;
    public open_read_delegation4 read;
    public open_write_delegation4 write;
    public open_none_delegation4 od_whynone;

    public open_delegation4() {
    }

    public open_delegation4(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    @Override
    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeInt(delegation_type);
        switch ( delegation_type ) {
        case open_delegation_type4.OPEN_DELEGATE_NONE:
            break;
        case open_delegation_type4.OPEN_DELEGATE_READ:
            read.xdrEncode(xdr);
            break;
        case open_delegation_type4.OPEN_DELEGATE_WRITE:
            write.xdrEncode(xdr);
            break;
        case open_delegation_type4.OPEN_DELEGATE_NONE_EXT:
            od_whynone.xdrEncode(xdr);
            break;
        }
    }

    @Override
    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        delegation_type = xdr.xdrDecodeInt();
        switch ( delegation_type ) {
        case open_delegation_type4.OPEN_DELEGATE_NONE:
            break;
        case open_delegation_type4.OPEN_DELEGATE_READ:
            read = new open_read_delegation4(xdr);
            break;
        case open_delegation_type4.OPEN_DELEGATE_WRITE:
            write = new open_write_delegation4(xdr);
            break;
        case open_delegation_type4.OPEN_DELEGATE_NONE_EXT:
            od_whynone = new open_none_delegation4(xdr);
            break;
        }
    }

}
// End of open_delegation4.java
