/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;
import org.dcache.xdr.*;
import java.io.IOException;

public class open_to_lock_owner4 implements XdrAble {
    public seqid4 open_seqid;
    public stateid4 open_stateid;
    public seqid4 lock_seqid;
    public lock_owner4 lock_owner;

    public open_to_lock_owner4() {
    }

    public open_to_lock_owner4(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    @Override
    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        open_seqid.xdrEncode(xdr);
        open_stateid.xdrEncode(xdr);
        lock_seqid.xdrEncode(xdr);
        lock_owner.xdrEncode(xdr);
    }

    @Override
    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        open_seqid = new seqid4(xdr);
        open_stateid = new stateid4(xdr);
        lock_seqid = new seqid4(xdr);
        lock_owner = new lock_owner4(xdr);
    }

}
// End of open_to_lock_owner4.java
