/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;
import org.dcache.xdr.*;
import java.io.IOException;

public class prev_entry4 implements XdrAble {
    public notify_entry4 pe_prev_entry;
    public nfs_cookie4 pe_prev_entry_cookie;

    public prev_entry4() {
    }

    public prev_entry4(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        pe_prev_entry.xdrEncode(xdr);
        pe_prev_entry_cookie.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        pe_prev_entry = new notify_entry4(xdr);
        pe_prev_entry_cookie = new nfs_cookie4(xdr);
    }

}
// End of prev_entry4.java
