/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;
import org.dcache.xdr.*;
import java.io.IOException;

public class referring_call_list4 implements XdrAble {
    public sessionid4 rcl_sessionid;
    public referring_call4 [] rcl_referring_calls;

    public referring_call_list4() {
    }

    public referring_call_list4(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    @Override
    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        rcl_sessionid.xdrEncode(xdr);
        { int $size = rcl_referring_calls.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { rcl_referring_calls[$idx].xdrEncode(xdr); } }
    }

    @Override
    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        rcl_sessionid = new sessionid4(xdr);
        { int $size = xdr.xdrDecodeInt(); rcl_referring_calls = new referring_call4[$size]; for ( int $idx = 0; $idx < $size; ++$idx ) { rcl_referring_calls[$idx] = new referring_call4(xdr); } }
    }

}
// End of referring_call_list4.java
