/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;
import org.dcache.xdr.*;
import java.io.IOException;

public class retention_get4 implements XdrAble {
    public uint64_t rg_duration;
    public nfstime4 [] rg_begin_time;

    public retention_get4() {
    }

    public retention_get4(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        rg_duration.xdrEncode(xdr);
        { int $size = rg_begin_time.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { rg_begin_time[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        rg_duration = new uint64_t(xdr);
        { int $size = xdr.xdrDecodeInt(); rg_begin_time = new nfstime4[$size]; for ( int $idx = 0; $idx < $size; ++$idx ) { rg_begin_time[$idx] = new nfstime4(xdr); } }
    }

}
// End of retention_get4.java
