/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;
/**
 * Enumeration (collection of constants).
 */
public interface secinfo_style4 {

    public static final int SECINFO_STYLE4_CURRENT_FH = 0;
    public static final int SECINFO_STYLE4_PARENT = 1;

}
// End of secinfo_style4.java
