/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;
import org.dcache.xdr.*;
import java.io.IOException;

public class server_owner4 implements XdrAble {
    public uint64_t so_minor_id;
    public byte [] so_major_id;

    public server_owner4() {
    }

    public server_owner4(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    @Override
    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        so_minor_id.xdrEncode(xdr);
        xdr.xdrEncodeDynamicOpaque(so_major_id);
    }

    @Override
    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        so_minor_id = new uint64_t(xdr);
        so_major_id = xdr.xdrDecodeDynamicOpaque();
    }

}
// End of server_owner4.java
