/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;
import org.dcache.chimera.nfs.v4.xdr.SEQUENCE4res;
import org.dcache.xdr.*;
import java.io.IOException;

public class ssr_digest_input4 implements XdrAble {
    public SEQUENCE4res sdi_seqres;

    public ssr_digest_input4() {
    }

    public ssr_digest_input4(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    @Override
    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        sdi_seqres.xdrEncode(xdr);
    }

    @Override
    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        sdi_seqres = new SEQUENCE4res(xdr);
    }

}
// End of ssr_digest_input4.java
