/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;

import java.io.IOException;

import org.dcache.xdr.OncRpcException;
import org.dcache.xdr.XdrAble;
import org.dcache.xdr.XdrDecodingStream;
import org.dcache.xdr.XdrEncodingStream;

public class ssv_seal_plain_tkn4 implements XdrAble {
    public byte [] sspt_confounder;
    public uint32_t sspt_ssv_seq;
    public byte [] sspt_orig_plain;
    public byte [] sspt_pad;

    public ssv_seal_plain_tkn4() {
    }

    public ssv_seal_plain_tkn4(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    @Override
    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeDynamicOpaque(sspt_confounder);
        sspt_ssv_seq.xdrEncode(xdr);
        xdr.xdrEncodeDynamicOpaque(sspt_orig_plain);
        xdr.xdrEncodeDynamicOpaque(sspt_pad);
    }

    @Override
    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        sspt_confounder = xdr.xdrDecodeDynamicOpaque();
        sspt_ssv_seq = new uint32_t(xdr);
        sspt_orig_plain = xdr.xdrDecodeDynamicOpaque();
        sspt_pad = xdr.xdrDecodeDynamicOpaque();
    }

}
// End of ssv_seal_plain_tkn4.java
