/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;
import org.dcache.xdr.*;
import java.io.IOException;

public class ssv_mic_plain_tkn4 implements XdrAble {
    public uint32_t smpt_ssv_seq;
    public byte [] smpt_orig_plain;

    public ssv_mic_plain_tkn4() {
    }

    public ssv_mic_plain_tkn4(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    @Override
    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        smpt_ssv_seq.xdrEncode(xdr);
        xdr.xdrEncodeDynamicOpaque(smpt_orig_plain);
    }

    @Override
    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        smpt_ssv_seq = new uint32_t(xdr);
        smpt_orig_plain = xdr.xdrDecodeDynamicOpaque();
    }

}
// End of ssv_mic_plain_tkn4.java
