/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;
import org.dcache.xdr.*;
import java.io.IOException;

public class utf8str_cs implements XdrAble {

    public utf8string value;

    public utf8str_cs() {
    }

    public utf8str_cs(String s) {
        this.value = new utf8string(s);
    }

    public utf8str_cs(utf8string value) {
        this.value = value;
    }

    public utf8str_cs(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    @Override
    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        value.xdrEncode(xdr);
    }

    @Override
    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        value = new utf8string(xdr);
    }

    @Override
    public String toString() {
        return value.toString();
    }
}
// End of utf8str_cs.java
