/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;
/**
 * Enumeration (collection of constants).
 */
public interface why_no_delegation4 {

    public static final int WND4_NOT_WANTED = 0;
    public static final int WND4_CONTENTION = 1;
    public static final int WND4_RESOURCE = 2;
    public static final int WND4_NOT_SUPP_FTYPE = 3;
    public static final int WND4_WRITE_DELEG_NOT_SUPP_FTYPE = 4;
    public static final int WND4_NOT_SUPP_UPGRADE = 5;
    public static final int WND4_NOT_SUPP_DOWNGRADE = 6;
    public static final int WND4_CANCELED = 7;
    public static final int WND4_IS_DIR = 8;

}
// End of why_no_delegation4.java
