/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;

import java.io.IOException;
import java.nio.ByteBuffer;

import org.dcache.xdr.OncRpcException;
import org.dcache.xdr.XdrAble;
import org.dcache.xdr.XdrDecodingStream;
import org.dcache.xdr.XdrEncodingStream;

public class WRITE4args implements XdrAble {
    public stateid4 stateid;
    public offset4 offset;
    public int stable;
    public ByteBuffer data;

    public WRITE4args() {
    }

    public WRITE4args(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    @Override
    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        stateid.xdrEncode(xdr);
        offset.xdrEncode(xdr);
        xdr.xdrEncodeInt(stable);
        xdr.xdrEncodeByteBuffer(data);
    }

    @Override
    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        stateid = new stateid4(xdr);
        offset = new offset4(xdr);
        stable = xdr.xdrDecodeInt();
        data = xdr.xdrDecodeByteBuffer();
    }

}
// End of WRITE4args.java
