/*
 * Automatically generated by jrpcgen 1.0.7 on 2/21/09 1:22 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.dcache.chimera.nfs.v4.xdr;

import java.io.IOException;

import org.dcache.xdr.OncRpcException;
import org.dcache.xdr.XdrAble;
import org.dcache.xdr.XdrDecodingStream;
import org.dcache.xdr.XdrEncodingStream;

public class WRITE4resok implements XdrAble {
    public count4 count;
    public int committed;
    public verifier4 writeverf;

    public WRITE4resok() {
    }

    public WRITE4resok(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    @Override
    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        count.xdrEncode(xdr);
        xdr.xdrEncodeInt(committed);
        writeverf.xdrEncode(xdr);
    }

    @Override
    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        count = new count4(xdr);
        committed = xdr.xdrDecodeInt();
        writeverf = new verifier4(xdr);
    }

}
// End of WRITE4resok.java
