#!/usr/bin/env sh
# $Id: dc_check,v 1.2 2003-10-16 08:58:40 tigran Exp $
#
dccp -P -t -1 $*

if test $? -eq 0
then
    r="passed"
else
    r="FAILED"
fi

f=$#
# Bash: echo Check $r for file \"${!f}\"

eval p=\$$f
echo Check $r for file \"$p\"
