#!/bin/sh
# $Id: srm-tomcat,v 1.4 2006-10-18 16:54:33 timur Exp $
#
# chkconfig: - 91 9
# description: srm tomcat startup script
#

cmd1=$1

if [ -r /usr/etc/setupSrmTomcat ] ; then
  . /usr/etc/setupSrmTomcat
fi

cd /opt/d-cache/libexec/apache-tomcat-5.5.20/bin

case $cmd1 in
  start)
        ./startup.sh
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && touch /var/lock/subsys/srm-tomcat
        ;;
  stop)
         ./shutdown.sh
          RETVAL=$?
          echo
          [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/srm-tomcat
          ;;
  restart|reload)
        $0 stop
        $0 start
        RETVAL=$?
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac
exit 0

